services:

  postgres_db:
    image: postgres:14
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "$${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      retries: 5
    networks:
      - real-time-network 
  spark-master:
    image: my-spark-image:1.2
    container_name: spark-master
    user: root
    ports:
      - "7077:7077"
      - "8081:8080"
      - "4040:4040"
      - "9095:9095"
    env_file:
      - .env
    volumes:
      - ./spark/apps:/opt/real-time-spark/spark/apps
      - ./spark/resources:/opt/real-time-spark/spark/resources 
      - ./e-commerce-user-events:/opt/real-time-spark/e-commerce-user-events
      - ./spark/checkpoints:/opt/real-time-spark/tmp/checkpoints
      - ./spark/conf:/opt/spark/conf
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

    networks:
      - real-time-network
  spark-worker:
    image: my-spark-image:1.2
    container_name: spark-worker
    user: root
    ports:
      - "9091:8081"
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077


    volumes:
      - ./spark/apps:/opt/real-time-spark/spark/apps
      - ./spark/resources:/opt/real-time-spark/spark/resources 
      - ./e-commerce-user-events:/opt/real-time-spark/e-commerce-user-events
      - ./spark/checkpoints:/opt/real-time-spark/tmp/checkpoints
    networks:
      - real-time-network
    
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - spark-master
    networks:
      - real-time-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dsh
    ports:
      - "3000:3000"  # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - real-time-network
    volumes:
      - grafana-storage:/var/lib/grafana  # persistent storage for dashboards

  broker:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS:  1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LOG_RETENTION_HOURS: 48
    networks:
      - real-time-network
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/broker/29092' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  kafka-UI:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-UI
    depends_on:
      - broker
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    networks:
      - real-time-network



networks:
  real-time-network:

volumes:
  pgdata:
  grafana-storage: